Kp = 0.8; 
T = 0.25; 
Ts = 0.04;
G = tf(Kp, [T 1]);
figure(1);
step(G);
title('Eksperiment: STEP odziv samog objekta');
xlabel('Vreme [s]'); ylabel('Odziv y(t)');
grid on;
Kc_p = 5.0;
W_p = feedback(Kc_p * G, 1);
Kc_pi = 3.0; 
Ti = 0.25;
C_pi = tf(Kc_pi * [Ti 1], [Ti 0]);
W_pi = feedback(C_pi * G, 1);
figure(2);
step(W_p, 'r', W_pi, 'b');
title('Poredjenje P i PI regulatora');
legend('P regulator (Kc=5, ostaje greska)', 'PI regulator (Kc=3, Ti=0.25, nema greske)');
xlabel('Vreme [s]'); ylabel('Odziv y(t)');
grid on;